//
//  RecoveryAttemper.swift
//  RecoverableError
//
//  Created by Aleksandr Lavrinenko on 15.02.2020.
//  Copyright Â© 2020 Aleksandr Lavrinenko. All rights reserved.
//

import Foundation

struct RecoveryAttemper {
	private let recoveryOptions: [RecoveryOptions]

	var recoveryOptionsText: [String] {
		return recoveryOptions.map({ $0.title })
	}

	init(recoveryOptions: [RecoveryOptions]) {
		self.recoveryOptions = recoveryOptions
	}

	func attemptRecovery(fromError error: Error, optionIndex: Int) -> Bool {
		let option = recoveryOptions[optionIndex]
		switch option {
		case .tryAgain(let action),
			 .freeSpace(let action),
			 .buyMoreSpace(let action):
			action()
			return true
		case .custom(_, let action):
			action()
			return true
		case .cancel:
			return false
		}
	}

	static func tryAgainAttempter(block: @escaping (() -> Void)) -> Self {
		return RecoveryAttemper(recoveryOptions: [.cancel, .tryAgain(action: block)])
	}

	static func cancalableAttemter(options: [RecoveryOptions]) -> Self {
		return RecoveryAttemper(recoveryOptions: [.cancel] + options)
	}
}
